import 'dart:collection';

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';
import 'package:spreadsheet_data_extractor/src/utils/excel_decoder/byte_worksheet_parser.dart';
import 'package:spreadsheet_data_extractor/src/utils/excel_decoder/worksheet.dart';
import 'package:spreadsheet_data_extractor/src/utils/grid_related_utils.dart';

/// This file is generated when running flutter pub run build_runner build or flutter pub run build_runner watch
part 'models.g.dart';

/// Generated by the Build Value Template: bvs (Built Value Serializers)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
@SerializersFor([
  SingleCell,
  CombinedCell,
  CellSelection,
  ImportCellsTask,
  ImportExcelSheetsTask,
  ImportExcelFilesTask,
  TaskList,
  ModifiedRow,
  ExcelSheet,
  ExcelFileModel,
  CellIndexModel,
])
final Serializers serializers =
    (_$serializers.toBuilder()..addPlugin(StandardJsonPlugin())).build();

abstract class CellIndexModel
    implements Built<CellIndexModel, CellIndexModelBuilder> {
  int get y;
  int get x;

  CellIndexModel._();
  factory CellIndexModel([void Function(CellIndexModelBuilder) updates]) =
      _$CellIndexModel;

  static Serializer<CellIndexModel> get serializer =>
      _$cellIndexModelSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class ExcelSheet implements Built<ExcelSheet, ExcelSheetBuilder> {
  int get maxRows;
  int get maxCols;
  String get sheetName;
  BuiltMap<int, BuiltMap<int, String>> get data;

  BuiltMap<int, BuiltMap<int, CellIndexModel>> get spanCells;

  ExcelSheet._();
  factory ExcelSheet([void Function(ExcelSheetBuilder) updates]) = _$ExcelSheet;

  static Serializer<ExcelSheet> get serializer => _$excelSheetSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class ExcelFileModel
    implements Built<ExcelFileModel, ExcelFileModelBuilder> {
  String get name;
  String get path;
  BuiltMap<String, ExcelSheet> get sheets;

  ExcelFileModel._();
  factory ExcelFileModel([void Function(ExcelFileModelBuilder) updates]) =
      _$ExcelFileModel;

  static Serializer<ExcelFileModel> get serializer =>
      _$excelFileModelSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class TaskList implements Built<TaskList, TaskListBuilder> {
  BuiltList<ImportExcelFilesTask> get childTasks;

  TaskList._();
  factory TaskList([void Function(TaskListBuilder) updates]) = _$TaskList;

  static Serializer<TaskList> get serializer => _$taskListSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class ImportExcelFilesTask
    implements Built<ImportExcelFilesTask, ImportExcelFilesTaskBuilder> {
  BuiltSet<String> get excelFilePaths;

  BuiltList<ImportExcelSheetsTask> get childTasks;

  ImportExcelFilesTask._();
  factory ImportExcelFilesTask([
    void Function(ImportExcelFilesTaskBuilder) updates,
  ]) = _$ImportExcelFilesTask;

  static Serializer<ImportExcelFilesTask> get serializer =>
      _$importExcelFilesTaskSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class ModifiedRow implements Built<ModifiedRow, ModifiedRowBuilder> {
  BuiltMap<int, String> get modifiedCells;

  ModifiedRow._();
  factory ModifiedRow([void Function(ModifiedRowBuilder) updates]) =
      _$ModifiedRow;

  static Serializer<ModifiedRow> get serializer => _$modifiedRowSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class ImportExcelSheetsTask
    implements Built<ImportExcelSheetsTask, ImportExcelSheetsTaskBuilder> {
  BuiltList<ImportCellsTask> get childTasks;

  BuiltMap<String, BuiltSet<String>> get sheetNamesByExcelFilePath;

  ImportExcelSheetsTask._();
  factory ImportExcelSheetsTask([
    void Function(ImportExcelSheetsTaskBuilder) updates,
  ]) = _$ImportExcelSheetsTask;

  static Serializer<ImportExcelSheetsTask> get serializer =>
      _$importExcelSheetsTaskSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class ImportCellsTask
    implements Built<ImportCellsTask, ImportCellsTaskBuilder> {
  BuiltList<ImportCellsTask> get childTasks;

  String? get typedValue;

  bool? get shiftingLocked;

  CellSelection get cellSelection;

  ImportCellsTask._();
  factory ImportCellsTask([void Function(ImportCellsTaskBuilder) updates]) =
      _$ImportCellsTask;

  static Serializer<ImportCellsTask> get serializer =>
      _$importCellsTaskSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class CellSelection
    implements Built<CellSelection, CellSelectionBuilder> {
  BuiltSet<CellBase> get cells;

  CellSelection._();
  factory CellSelection([void Function(CellSelectionBuilder) updates]) =
      _$CellSelection;

  static Serializer<CellSelection> get serializer => _$cellSelectionSerializer;

  SelectedCellGrid toViewModel() {
    List<SelectedCell> selectedCells = [];

    for (final cell in cells) {
      if (cell is SingleCell) {
        selectedCells.add(SelectedCell.fromSingleCell(cell));
      } else if (cell is CombinedCell) {
        final partsOfCombinedCell = cell.cells;

        final addedNeighborlessCells = Queue<SelectedCell>();
        for (final partOfCombinedCell in partsOfCombinedCell) {
          final selectedCell = SelectedCell.fromSingleCell(partOfCombinedCell);

          selectedCells.add(selectedCell);
          addedNeighborlessCells.add(selectedCell);
        }

        while (addedNeighborlessCells.isNotEmpty) {
          final cell = addedNeighborlessCells.removeFirst();

          for (var possibleNeighbor in addedNeighborlessCells) {
            cell.updateNeighbors(possibleNeighbor);
          }
        }
      }
    }

    return SelectedCellGrid.fromCells(selectedCells);
  }
}

@BuiltValue(instantiable: false)
abstract class CellBase {
  String getValue(ByteParsedWorksheet sheet);
  String getExcelCellId();
  List<CellIndex> getCellIndex();
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets
abstract class SingleCell
    implements CellBase, Built<SingleCell, SingleCellBuilder> {
  int get x;
  int get y;

  @override
  String getValue(ByteParsedWorksheet sheet, {bool trim = true}) {
    final cell = sheet.cell(columnIndex: x, rowIndex: y);

    if (cell == null) {
      return "";
    }

    final cellSpan = cell.cellSpan;
    final dynamic cellValue;
    if (cellSpan != null) {
      cellValue =
          sheet
              .cell(
                columnIndex: cellSpan.start.columnIndex,
                rowIndex: cellSpan.start.rowIndex,
              )!
              .value;
    } else {
      cellValue = cell.value;
    }

    final text = cellValue.toString();

    if (trim) {
      final withoutLinebreaks = text.split("\n").fold<String>("", (
        previousValue,
        text,
      ) {
        final trimmedText = text.trim();
        if (previousValue.endsWith("-")) {
          return "$previousValue$trimmedText";
        } else {
          return "$previousValue $trimmedText";
        }
      });
      return withoutLinebreaks;
    } else {
      return text;
    }
  }

  //const SingleCell({required this.x, required this.y});

  @override
  String getExcelCellId() => CellIndex(rowIndex: y, columnIndex: x).cellId;
  @override
  List<CellIndex> getCellIndex() => [CellIndex(rowIndex: y, columnIndex: x)];

  SingleCell._();
  factory SingleCell([void Function(SingleCellBuilder) updates]) = _$SingleCell;

  static Serializer<SingleCell> get serializer => _$singleCellSerializer;
}

/// Generated by the Build Value Template: bvts (Built Value Type Serializable)
/// Plugin: Built Value Snippets
/// https://plugins.jetbrains.com/plugin/13786-built-value-snippets

abstract class CombinedCell
    implements CellBase, Built<CombinedCell, CombinedCellBuilder> {
  BuiltSet<SingleCell> get cells;
  String get separator;
  bool get trimValues;

  @override
  String getValue(ByteParsedWorksheet sheet) {
    List<SingleCellSheetCellPair> uniqueCells = [];

    for (var cell in cells) {
      final sheetCell = sheet.cell(rowIndex: cell.x, columnIndex: cell.y);

      if (sheetCell == null) {
        continue;
      }

      final selectedCellSheetCellPair = SingleCellSheetCellPair(
        cell,
        sheetCell,
      );

      var cellSpan = sheetCell.cellSpan;

      if (cellSpan == null) {
        uniqueCells.add(selectedCellSheetCellPair);
        continue;
      }

      final combinedCellAlreadyProcessed = uniqueCells.any(
        (uniqueCell) => uniqueCell.sheetCell.cellSpan == sheetCell.cellSpan,
      );
      if (combinedCellAlreadyProcessed) {
        continue;
      }

      uniqueCells.add(selectedCellSheetCellPair);
    }

    final combinedValue = uniqueCells
        .map((cell) => cell.singleCell.getValue(sheet))
        .where((text) => text.isNotEmpty == true)
        .join(separator);
    return combinedValue;
  }

  @override
  String getExcelCellId() =>
      "(${cells.map((innerCell) => innerCell.getExcelCellId()).join(",")})";
  @override
  List<CellIndex> getCellIndex() =>
      cells.map((cell) => cell.getCellIndex().single).toList();

  //const CombinedCell(this.cells, {this.separator = " ", this.trimValues = true});

  static void _initializeBuilder(CombinedCellBuilder b) =>
      b
        ..separator = " "
        ..trimValues = true;

  CombinedCell._();
  factory CombinedCell([void Function(CombinedCellBuilder) updates]) =
      _$CombinedCell;

  static Serializer<CombinedCell> get serializer => _$combinedCellSerializer;
}

class SingleCellSheetCellPair {
  final SingleCell singleCell;
  final Cell sheetCell;

  SingleCellSheetCellPair(this.singleCell, this.sheetCell);
}
